name: Docker Image  Github

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: it19091358/ctse:latest
    # - uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_HOST: ${{ secrets.KUBE_HOST }}
    #     KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
    #     KUBE_USERNAME: ${{ secrets.KUBE_USERNAME }}
    #     KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        
    #   with:
    #     args: get pods  
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get namespaces
        

       
   
      
  

