name: Docker Image  Github

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: it19091358/ctse:latest
    # - uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   # with:
    #   #   args: get namespaces
    #   with:
    #     args: apply -f k8s/
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        echo ${{ secrets.KUBE_CONFIG }} 

    - name: Use Context
      run: kubectl config use-context octobay-api
    - name: Deploy to k8s
      run: kubectl apply -f k8s/


